### ISSUE TITLE
warning: dropping unclosed device

### ISSUE THREAD

**Issue by danshapero** [jichu4n/JFBView#19]
When opening a PDF, I get `warning: dropping unclosed device` printed on screen; when I hit escape, the message stays up for a second longer and then goes away. It looks like the warning comes from the call [here](https://github.com/jichu4n/JFBView/blob/master/pdf_document.cpp#L198) to [this line](https://github.com/muennich/mupdf/blob/4d473e7f6a6ec72265270c03a26b48e27db11282/source/fitz/device.c#L67) of the MuPDF function `fz_drop_device`.

I'm using Arch Linux on ARM and MuPDF 1.13.  Let me know if there's anything more I can do that would help diagnose the issue!

**Comment by jichu4n** [comment]
Thanks a lot for reporting this and for the pointers to the code! Fixing this in PR #21 .
