### ISSUE TITLE
failure to make on Deb9

### ISSUE THREAD

**Issue by kalpha2** [jichu4n/jfbview#29]
following the instructions and installing the dependencies first, 
which included
The following NEW packages will be installed:
  libjbig2dec0-dev libmupdf-dev libopenjp2-7-dev
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
and reported no errors

then make fails with 
/usr/bin/ld: cannot find -lopenjpeg

**Comment by kalpha2** [comment]
I got past the issue by manually updating the config.mk which had
OPENJP2 = openjpeg
and changed it to 
OPENJP2 = openjp2
So it builds, but when it runs, I get a distorted screen, it does appear to be attempting to render something from mixture of grey boxes and blacks lines that are present in pdf, zooming is working but is all distorted and q does quit. But useless otherwise

**Comment by Ed-Infrared** [comment]
Thank you for your comment, it helped me to compile on debian buster (deb10).
After compiling all worked well.

**Comment by jichu4n** [comment]
Thanks all! As of the [0.6.0 release](https://github.com/jichu4n/jfbview/releases), there are now pre-built `.deb` packages available for Debian 9 and 10, as well as [a build script](https://github.com/jichu4n/jfbview/blob/master/packaging/build-package-deb.sh) if needing to build from source.
