### ISSUE TITLE
<stropts.h>, No Such File Or Directory, Could Not Find ioctl After Creation Of stropts.h

### ISSUE THREAD

**Issue by Rubix982** [jichu4n/jfbview#31]
Hi!

I'm running Arch Linux, with G++ 9.2.0, kernel info as follows:

Linux archlinux 5.4.10-arch1-1 #1 SMP PREEMPT Thu, 09 Jan 2020 10:14:29 +0000 x86_64 GNU/Linux

System was just updated with sudo pacman -Syu, 2-3 hours earlier.

I opened a terminal in the the main folder of 'yay', and ran 
'''
yay -S jfbiew
'''

_**yay**_ started to build in the following below directory.

/home/saif/.cache/yay/jfbview/src/jfbview-0.5.6

Towards the end, I ran into the error of 'main.cpp:<stropts.h>, no such file or directory', during the build process.

To solve that, I ran the risk of running,
'''
touch /usr/include/stropts.h
'''

which solved this problem. After that, I ran 'yay -S jfbview' again, and this time, I was thrown the error of, 'ioctl was not declared in the scope'. 

Googling this issue revealed that it needed a header file, #include <sys/ioctls.h>, but I do not know where to make this addition to, or which lines to edit to fix this.

I tried cd'ing into where the build was being made, and inserted a line for the header file, but I'm not sure if that's correct because the end result is still that the build stopped halfway through in main.cpp.

Screenshots are attached as imgur links,
1): [https://imgur.com/Ra3doab](Accepting installation process)
2): [https://imgur.com/armXQtL](Error thrown during build) 

Thank you for your time!

**Comment by Ma27** [comment]
The `<stropts.h>` was removed in glibc 2.30 (https://savannah.gnu.org/forum/forum.php?forum_id=9515) which is IIRC used by ArchLinux by default.

It should be sufficient to replace the `<stropts.h>` inclusion with `<sys/ioctl.h>`.

**Comment by Rubix982** [comment]
Hi @Ma27 ! 
The file that causes the issue and contains `<stropts.h>` is main.cpp which is built during the process, so it stops the process halfway through. Replacing `<stropts.h>` with `<sys/loctl.h>` doesn't really help because the application hasn't been built properly - the solution seems to me to a modification with the makefiles - as far as I know.

Thanks.

**Comment by Ma27** [comment]
I mean patching `main.cpp` and replace the inclusion of `stropts.h` there with `sys/ioctl.h`.

**Comment by Rubix982** [comment]
Alright, I'll look into it. Thank you.

**Comment by jichu4n** [comment]
Thanks a lot @Ma27 and @Rubix982 ! Merged suggested fix in PR #32 and will make a new release.
