### ISSUE TITLE
a big thank you for this project

### ISSUE THREAD

**Issue by m040601** [jichu4n/jfbview#33]
Just want to upvote this project and thank farseerfc (jichu4n) for creating the AUR package.

I actually had it bookmarked long ago (2018), but only recently tested it and noticed it again because github alerted me of your 2020 commits. You should commit and release more often :-)

I works wonderfully in the console. The search and TOC functinality is very polished and usefull. Specially showing the search results in context. Very well done. Maybe you could add a screenshot or animation on the README highlighting all this. It really deserves it.

I also liked that you tried to somehow mimic the Zathura keybindings . and give the end user a very VIM like experience. Very appealing for the potential users of this tools. Instead of reinventing the wheel with yet another set of totally different keybindings.

I tested and use a lot of pdf and image console viewers like, http://www.kraxel.org/blog/linux/fbida/ (gives fbi and fbpdf on arch) and https://aur.archlinux.org/packages/fbpdf-git (fbpdf2).( Maybe you'd also challenge your self to make a nice image viewer for the console ?)

 Anyway this one is definetly the most polished. 
Any plans to add epub support (through mupdf ) ?
.
I also want to report that it compiles and works perfectly on the raspberry pi 2 and on ARM chromebooks, that is "armv7h".

So, to repeat @zertyz request, please update the PKGBUILD to include "armv6h" and "armv7h"

**Comment by jichu4n** [comment]
@m040601 Thanks for the encouraging words! Very much appreciated.

> Maybe you'd also challenge your self to make a nice image viewer for the console ?

jfbview is currently already able to view images (JPG, PNG etc).

> So, to repeat @zertyz request, please update the PKGBUILD to include "armv6h" and "armv7h"

Just published a new [0.6.0 release](https://github.com/jichu4n/jfbview/releases) with a lot of changes. I've also updated the `jfbview` AUR package to include `armv6h` and `armv7h` as you suggested (and also `aarch64) after CI and manual testing.

> Any plans to add epub support (through mupdf ) ?

Will definitely look into it. I'll leave this issue open to track.

**Comment by m040601** [comment]
> jfbview is currently already able to view images (JPG, PNG etc).

Would it be possible to make it display all the files in a folder (recursively)
Something like:

`jfbview -r /path/to/some-folder/full-of-images-or-pdfs/
`
or
`jfbview /path/to/some-folder/full-of-images-or-pdfs/*
`

Right now when you specify a folder or "*" you always get the message:
`Please specify exactly one input file. Try "-h" for help.
`

**Comment by jichu4n** [comment]
Hi @m040601! Could you help me understand what the expected behavior would be in that case? Is the intention that it'd automatically switch to file 2 when you reach the end of file 1 and so on?

**Comment by m040601** [comment]
> is the intention that it'd automatically switch to file 2 when you reach the end of file 1 and so on?

yes, something like that. If you keep pressing "n" or "Space" it opens the next file, "p" or "Backspace" the previous, and "q" quits.

Something like the way sxiv and feh do it:

`sxiv /path/to/folder-with-pictures/`

or recursevly

`sxiv -r /path/to/folder-containing-subfolders-with-pictures/`

man sxiv:

>        -r     Search the given directories recursively for images to view.

`feh /path/to/folder-with-pictures/`

recursevly

`feh -r /path/to/folder-containing-subfolders-with-pictures/`

man feh:

>     -r, --recursive
>              Recursively expand any directories in the command line arguments to the content of those directo‐
>              ries, all the way down to the bottom level.
>

**Comment by m040601** [comment]
> open more than one file at the time

I've decided to open a separate new issue for this request of mine, should that ever be considered

https://github.com/jichu4n/jfbview/issues/61
