### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Superpat** [jichu4n/JFBView#5]
Hello I tried using this today on ubuntu 15 and it seems like whenever I open a pdf I'm confronted with a blank terminal, I can still quit with q

**Comment by gaffatape** [comment]
Same here on Debian Stretch. Not a completely blank screen, but white with black static lines which is supposed to be the rendered text from the looks of it.

**Comment by maandree** [comment]
I hade the problem gaffatape describes, although to a lesser degree earlier on one of my computers.
It resolved itself either with a new version of linux or jfbview. I made a workaround: https://github.com/jichu4n/JFBView/pull/2

**Comment by DealPete** [comment]
Same problem here. I'm using Arch Linux, with i3 and xterm. I get a completely blank screen when I try to view a PDF.

**Comment by jichu4n** [comment]
@Superpat @DealPete This is a viewer for the Linux framebuffer, which typically means no X11. If you're running a window manager or X terminal, this is not for you.

**Comment by Superpat** [comment]
I've long come to that knowledge, but thanks anyways!
 
 
On Tue, Jun 21, 2016, at 09:54, Chuan Ji wrote:
> @Superpat[1] @DealPete[2] This is a viewer for the Linux framebuffer,
> which typically means no X11. If you're running a window manager or X
> terminal, this is not for you.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
>
 

Links:

  1. https://github.com/Superpat
  2. https://github.com/DealPete
  3. https://github.com/jichu4n/JFBView/issues/5#issuecomment-227502447
  4. https://github.com/notifications/unsubscribe/AEUsIwZPA-6eCx0ukS_dhu994zZn8njzks5qOBdhgaJpZM4FwbyX
