### ISSUE TITLE
build failure on Debian10

### ISSUE THREAD

**Issue by kalpha2** [jichu4n/jfbview#54]
I can confirm the deb already provided in the packaging folder works great under Debian 10.
But if I try to build myself I get
 sudo ./build-package-deb.sh 
+ install_build_deps
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ apt-get -qq update
+ apt-get -qq install -y build-essential cmake file libncurses-dev libncursesw5-dev libimlib2-dev
+ install_test_deps
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ apt-get -qq install -y libgtest-dev
+ dpkg -L libgtest-dev
+ grep -q 'libgtest\.a$'
+ gtest_root_flag=()
+ run_tests
++ dirname ./build-package-deb.sh
+ cd ./..
+ mkdir -p build_tests
+ cmake -H. -Bbuild_tests -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user1/jfbview-master/build_tests
+ cmake --build build_tests
[  0%] Built target jpdfcat
[  4%] Generating ../../vendor/mupdf/build/release
make[3]: *** No rule to make target 'libs'.  Stop.
make[2]: *** [vendor/CMakeFiles/vendor_mupdf.dir/build.make:61: ../vendor/mupdf/build/release] Error 2
make[1]: *** [CMakeFiles/Makefile2:987: vendor/CMakeFiles/vendor_mupdf.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by jichu4n** [comment]
Hi @kalpha2 ,

Ah I think it's because it's missing a step from the ["Source code" section](https://github.com/jichu4n/jfbview#source-code):
```
cd jfbview
git submodule update --init --recursive
```

I'll update the README to clarify.

**Comment by jichu4n** [comment]
Updated README in 7812e6f623bc834c92a8c1c00c30bea8118173b0 .

**Comment by kalpha2** [comment]
thankyou can confirm it builds all okay now.
