### ISSUE TITLE
Getting error when trying to open any pdf file

### ISSUE THREAD

**Issue by tail-devouring-dragon** [jichu4n/JFBView#7]
I am getting following error message every time:

Error initializing framebuffer: Permission denied
Segmentation fault (core dumped)

Any solutions?

**Comment by maandree** [comment]
Check that you have permission to read and write to /dev/fb0. Normally you need to be in the group `video`.

**Comment by tail-devouring-dragon** [comment]
Alright, I added myself in video, restarted, error went away but when I try to open pdf, I get black screen in terminal.

**Comment by maandree** [comment]
Don't know why that would happen. Have you tried multiple PDF:s?

**Comment by tail-devouring-dragon** [comment]
I tried multiple PDFs and multiple terminals, no luck.

**Comment by maandree** [comment]
Ah, I think you might have misunserstood the program. It does not work for terminals like GNOME Terminal, Konsole, Terminator, etc. Linux has a built-in terminal, it ­— and replacements for it like kmscon — are the terminals JFBBiew work on. You can read about it on https://en.wikipedia.org/wiki/Linux_console and on https://en.wikipedia.org/wiki/Virtual_console.

**Comment by tail-devouring-dragon** [comment]
Oh, yeah that must be it, I was trying to view pdfs on urxvt. Thank you for clarifying.
